name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn ci
        working-directory: ./server
      - run: yarn ci
        working-directory: ./client
      - run: yarn run build
        working-directory: ./client
      - run: yarn run server
        working-directory: ./server
